export const TRAVELS_LIST_REQUEST = "TRAVELS_LIST_REQUEST";
export const TRAVELS_LIST_SUCCESS = "TRAVELS_LIST_SUCCESS";
export const TRAVELS_LIST_FAIL = "TRAVELS_LIST_FAIL";

export const TRAVELS_RANDOM_REQUEST = "TRAVELS_RANDOM_REQUEST";
export const TRAVELS_RANDOM_SUCCESS = "TRAVELS_RANDOM_SUCCESS";
export const TRAVELS_RANDOM_FAIL = "TRAVELS_RANDOM_FAIL";

export const TRAVEL_DETAILS_REQUEST = "TRAVEL_DETAILS_REQUEST";
export const TRAVEL_DETAILS_SUCCESS = "TRAVEL_DETAILS_SUCCESS";
export const TRAVEL_DETAILS_FAIL = "TRAVEL_DETAILS_FAIL";
export const TRAVEL_DETAILS_RESET = "TRAVEL_DETAILS_RESET";

export const TRAVELS_TOP_RATED_REQUEST = "TRAVELS_TOP_RATED_REQUEST";
export const TRAVELS_TOP_RATED_SUCCESS = "TRAVELS_TOP_RATED_SUCCESS";
export const TRAVELS_TOP_RATED_FAIL = "TRAVELS_TOP_RATED_FAIL";
export const TRAVELS_TOP_RATED_RESET = "TRAVELS_TOP_RATED_RESET";

export const CREATE_REVIEW_REQUEST = "CREATE_REVIEW_REQUEST";
export const CREATE_REVIEW_SUCCESS = "CREATE_REVIEW_SUCCESS";
export const CREATE_REVIEW_FAIL = "CREATE_REVIEW_FAIL";
export const CREATE_REVIEW_RESET = "CREATE_REVIEW_RESET";

export const DELETE_TRAVEL_REQUEST = "DELETE_TRAVEL_REQUEST";
export const DELETE_TRAVEL_SUCCESS = "DELETE_TRAVEL_SUCCESS";
export const DELETE_TRAVEL_FAIL = "DELETE_TRAVEL_FAIL";

export const DELETE_ALL_TRAVELS_REQUEST = "DELETE_ALL_TRAVELS_REQUEST";
export const DELETE_ALL_TRAVELS_SUCCESS = "DELETE_ALL_TRAVELS_SUCCESS";
export const DELETE_ALL_TRAVELS_FAIL = "DELETE_ALL_TRAVELS_FAIL";

export const CREATE_TRAVEL_REQUEST = "CREATE_TRAVEL_REQUEST";
export const CREATE_TRAVEL_SUCCESS = "CREATE_TRAVEL_SUCCESS";
export const CREATE_TRAVEL_FAIL = "CREATE_TRAVEL_FAIL";
export const CREATE_TRAVEL_RESET = "CREATE_TRAVEL_RESET";

export const UPDATE_TRAVEL_REQUEST = "UPDATE_TRAVEL_REQUEST";
export const UPDATE_TRAVEL_SUCCESS = "UPDATE_TRAVEL_SUCCESS";
export const UPDATE_TRAVEL_FAIL = "UPDATE_TRAVEL_FAIL";
export const UPDATE_TRAVEL_RESET = "UPDATE_TRAVEL_RESET";

export const TRAVEL_RECOMMENDATIONS_REQUEST = "TRAVEL_RECOMMENDATIONS_REQUEST";
export const TRAVEL_RECOMMENDATIONS_SUCCESS = "TRAVEL_RECOMMENDATIONS_SUCCESS";
export const TRAVEL_RECOMMENDATIONS_FAIL = "TRAVEL_RECOMMENDATIONS_FAIL";
export const TRAVEL_RECOMMENDATIONS_RESET = "TRAVEL_RECOMMENDATIONS_RESET";
